title: Kaido's Notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kaidohex.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kaidohex
github_username: kaidohex

# Use Just the Docs theme
remote_theme: "just-the-docs/just-the-docs"

# Enable search and navigation
search_enabled: true
aux_links:
  "GitHub Repository":
    - "https://github.com/kaidohex"

# Sidebar navigation settings
nav_sort: case_insensitive
nav_order: 1
nav_exclude: []

# Exclude from processing
exclude:
  - _drafts/
